[build]
  functions = "functions"
  publish = "."

# Add CORS headers for functions responses (browse-friendly)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Ensure clean URLs
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
